### ISSUE TITLE
Ping Failed

### ISSUE THREAD

**Issue by Murdi44** [Enukio/NodepayBot#1]
[Nodepay] | 2024-11-30 18:52:06 | ERROR   | 183 | Ping Failed, Reason: No response from server, Proxy: [HIDDEN]

how to fix?

**Comment by Enukio** [comment]
> [Nodepay] | 2024-11-30 18:52:06 | ERROR | 183 | Ping Failed, Reason: No response from server, Proxy: [HIDDEN]
> 
> how to fix?

Script has been updated
